/**
 * Types for the shared board document `boards/default`.
 *
 * The old app and this app read and write the SAME Firestore document at the
 * same time. Every stored item therefore carries an index signature
 * (`[extra: string]: unknown`) so fields written by the other app (or by a
 * future version) survive a normalize/merge round-trip untouched.
 *
 * Timestamps are epoch milliseconds (numbers). Dates are "YYYY-MM-DD" strings.
 * Times are "HH:MM" strings.
 */

/** Epoch milliseconds. */
export type Millis = number;
/** "YYYY-MM-DD" */
export type DateKey = string;

export interface Extra {
  [extra: string]: unknown;
}

/** A coloured option: Gantt status, PED status or Creator Calendar status. */
export interface Status extends Extra {
  name: string;
  color: string;
}

export interface Project extends Extra {
  id: string;
  name: string;
  color: string;
}

export interface Social extends Extra {
  id: string;
  label: string;
  /** Two letter badge, upper case ("IG", "TT"). */
  short: string;
  color: string;
}

/** An image/video attached to a task or PED post (see serializableAssetItems in the old app). */
export interface AssetItem extends Extra {
  type: string;
  src: string;
  fallback: string;
  original: string;
  label: string;
}

export interface Subtask extends Extra {
  id: string;
  title: string;
  members: string[];
  done: boolean;
}

export interface PedComment extends Extra {
  id: string;
  text: string;
  mentions: string[];
  createdAt: Millis;
}

/**
 * Creator workflow action stored in `Task.creatorAction`.
 * Child tasks are generated from a parent task whose label is "creator".
 */
export type CreatorAction =
  | "contact"
  | "ask-ok"
  | "contract"
  | "brief"
  | "giorgia"
  | "video"
  | "send-video-alice"
  | "publish";

export interface Task extends Extra {
  id: string;
  projectId: string;
  /** Title in the language it was typed. */
  name: string;
  /** English title (the old app auto-translated). May be "" . */
  nameEn: string;
  members: string[];
  /** Status NAME (not an id). */
  status: string;
  start: DateKey;
  end: DateKey;
  /** Free text: link or notes. */
  info: string;
  /** Free label: "creator", workflow labels, "Video in store", "Pubblicazione"... */
  label: string;
  subtasks: Subtask[];
  createdAt?: Millis;
  updatedAt: Millis;

  // PED (editorial plan) fields stored on the task
  pedEnabled: boolean;
  pedAutoDismissed: boolean;
  pedDate: DateKey;
  pedTime: string;
  pedTitle: string;
  /** Social ids. */
  pedSocial: string[];
  pedAsset: string;
  pedAssetItems: AssetItem[];
  pedCopy: string;

  // Creator Calendar fields
  creatorStatus: string;
  creatorStore: string;
  creatorTime: string;

  // Creator workflow children
  creatorParentId?: string;
  creatorAction?: CreatorAction | string;

  /** Set on tasks generated by the influencer type progress feature. */
  influencerProgressTypeKey?: string;
  /** Legacy flag read by normalizeData (maps to label "Video in store"). */
  hasHomeLabel?: boolean;
}

export interface PedPost extends Extra {
  id: string;
  /** Set when the post is the PED mirror of a Gantt task. */
  sourceTaskId: string;
  title: string;
  projectId: string;
  date: DateKey;
  time: string;
  status: string;
  members: string[];
  /** "Video" | "Static" | "Carousel" */
  format: PedFormat;
  /** Social ids. */
  social: string[];
  asset: string;
  assetItems: AssetItem[];
  copy: string;
  comments: PedComment[];
  subtasks: Subtask[];
  createdAt?: Millis;
  updatedAt: Millis;
}

export type PedFormat = "Video" | "Static" | "Carousel";

export type InfluencerFieldKey =
  | "name"
  | "city"
  | "target"
  | "type"
  | "ttProfile"
  | "igProfile"
  | "ttLink"
  | "igLink"
  | "output"
  | "price"
  | "status"
  | "where"
  | "when";

export interface Influencer extends Extra {
  id: string;
  updatedAt: Millis;
  /** Per field last-write timestamps used by the merge. */
  fieldUpdatedAt: Record<string, Millis>;
  sortOrder: number;
  name: string;
  city: string;
  target: string;
  type: string;
  ttProfile: string;
  igProfile: string;
  ttLink: string;
  igLink: string;
  output: string;
  price: string;
  status: string;
  where: string;
  when: string;

  contactTaskEnabled: boolean;
  contactTaskId: string;
  contactDate: DateKey;
  contactMember: string;
  contactProjectId: string;
  /** Date key the status became CONTACTED. */
  contactedAt: DateKey;
  /** Date key of the last status change (used by the 30-day "Ghosted" aging). */
  influencerUpdatedAt: DateKey;
  createdAt?: Millis;
}

export type InfluencerOptionKey = "city" | "target" | "type" | "status" | "where" | "when";

export interface InfluencerOption extends Extra {
  name: string;
  color: string;
  textColor: string;
  /** Only meaningful for the "type" list. */
  needed: number;
  previewVisible?: boolean;
  previewUpdatedAt?: Millis;
  deadline?: DateKey;
  projectId?: string;
  progressTaskId?: string;
}

export type InfluencerOptions = Record<InfluencerOptionKey, InfluencerOption[]> & Record<string, InfluencerOption[]>;
export type InfluencerDeletedOptions = Record<InfluencerOptionKey, string[]> & Record<string, string[]>;

export interface LedgerEntry {
  value: unknown;
  updatedAt: Millis;
}
/** influencer id -> field key -> last value written. */
export type InfluencerFieldLedger = Record<string, Record<string, LedgerEntry>>;

export type TypeProgressField = "visible" | "needed" | "deadline" | "projectId";
/** normalized type name key -> field -> entry */
export type InfluencerTypeProgressConfig = Record<string, Partial<Record<TypeProgressField, LedgerEntry>>>;

export type SettingMergeKey =
  | "members"
  | "statuses"
  | "pedStatuses"
  | "creatorStatuses"
  | "labels"
  | "formats"
  | "creatorStores"
  | "projects"
  | "socials"
  | "influencerOptions"
  | "influencerPreviewVisibility"
  | "influencerDeletedOptions"
  | "influencerColumnLabels";

export type SettingsUpdatedAt = Record<SettingMergeKey, Millis>;

export type DeletedKind = "tasks" | "pedPosts" | "influencers";
/** Tombstones: item id -> deletion time. */
export type DeletedIds = Record<DeletedKind, Record<string, Millis>>;

export interface BoardData extends Extra {
  /** Assignee names. */
  members: string[];
  statuses: Status[];
  pedStatuses: Status[];
  creatorStatuses: Status[];
  creatorStores: string[];
  /** Task labels (settings list). */
  labels: string[];
  formats: string[];
  socials: Social[];
  projects: Project[];
  tasks: Task[];
  pedPosts: PedPost[];
  influencers: Influencer[];
  influencerFieldLedger: InfluencerFieldLedger;
  influencerTypeProgressConfig: InfluencerTypeProgressConfig;
  influencerOptions: InfluencerOptions;
  influencerPreviewVisibility: Record<string, boolean>;
  influencerDeletedOptions: InfluencerDeletedOptions;
  /** column key -> user defined heading. */
  influencerColumnLabels: Record<string, string>;
  settingsUpdatedAt: SettingsUpdatedAt;
  deletedIds: DeletedIds;
}

/** One local undo/history entry ("before change" snapshot). Local only, never written to Firestore. */
export interface HistoryEntry {
  id: string;
  /** ISO timestamp. */
  savedAt: string;
  label: string;
  summary: string;
  data: BoardData;
}

/** Automatic protected snapshot (local IndexedDB/localStorage, and boardSafety* docs in Firestore). */
export interface SafetyBackup {
  id: string;
  revision: number;
  /** ISO timestamp. */
  savedAt: string;
  source: string;
  summary: string;
  score: number;
  data: BoardData;
  history: HistoryEntry[];
}

/** The Firestore document `boards/default`. */
export interface BoardDocument {
  data: BoardData;
  /** The old app always writes [] here; history is kept locally. */
  history: HistoryEntry[];
  revision: number;
  safetyRevision?: number;
  /** Firestore server timestamp (opaque to the data layer). */
  updatedAt?: unknown;
}

export type SyncStatus = "connecting" | "synced" | "saving" | "offline" | "error";

export type AuthState = "unknown" | "signed-out" | "signed-in";

export interface SyncState {
  auth: AuthState;
  /** False until the first data load finished (or failed over to local data). */
  ready: boolean;
  syncStatus: SyncStatus;
  /** Human readable English status line. */
  message: string;
  /** True when `message` describes a problem. */
  isError: boolean;
  /** Current board data (immutable snapshot: never mutate it, use `mutate`). */
  data: BoardData;
  history: HistoryEntry[];
  revision: number;
  canUndo: boolean;
  hasUnsyncedChanges: boolean;
  /** Last login error, "" if none. */
  authError: string;
  /** True when running against the demo (non Firebase) backend. */
  demo: boolean;
  /** True when the engine never writes (to Firestore or to this device). Edits are rejected. */
  readOnly: boolean;
}

/** Per collection ids touched by a save (used to protect local edits during merge). */
export interface DirtyIds {
  tasks: Set<string>;
  pedPosts: Set<string>;
  influencers: Set<string>;
}

/** Plain object standing in for the creator-options DOM controls of the old app. */
export interface CreatorControls {
  contact: { checked: boolean };
  askOk: { checked: boolean };
  contract: { checked: boolean };
  brief: { checked: boolean };
  giorgia: { checked: boolean };
  video: { checked: boolean };
  videoDate: { value: string };
  sendVideoAlice: { checked: boolean };
  sendVideoAliceDate: { value: string };
  publish: { checked: boolean };
  publishDate: { value: string };
}

/** Structured history diff (replaces the HTML/line based output of the old app). */
export type HistoryDiffKind = "GANTT task" | "PED post" | "Influencer" | "Project";
export type HistoryDiffChange = "added" | "changed" | "removed";
export interface HistoryDiffEntry {
  /** Collection label, same text as the old app ("GANTT task", "PED post"...). */
  kind: HistoryDiffKind;
  /** What happened to the item. */
  change: HistoryDiffChange;
  /** Display title of the item. */
  title: string;
  /** Field level changes, e.g. "status: TO DO → DONE" (empty for added/removed). */
  changes: string[];
}
